version: "3.8"
services:
  # The database service
  db:
    # Using the postgreSQL official image
    image: postgres
    # Rename it postgres to avoid being named 'db-1'
    container_name: postgres
    # Define every required environment variables
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    # Create a volume to persist database data
    volumes:
      - pgdata:/var/lib/postgresql/data
    # Link the network to the container
    networks:
      - backend
    # Always restart the database if it ever goes down
    restart: always
  # The app service
  jizo:
    # Rename it jizo to avoir being named `jizo-1`
    container_name: jizo
    # Point to the dev.Dockerfile used for the build
    build:
      # dev.Dockerfile which is located in the same directory as the docker-compose.yaml
      context: .
      dockerfile: docker/dev.Dockerfile
    # Exposing ports
    ports:
      - "9999:8000"
    # Mount the volume
    volumes:
      - .:/jizo
      - static_volume:/home/src/app/web/staticfiles
    # Command used to run the server
    command:
      python manage.py runserver 0.0.0.0:8000
    # Cannot be launched without the db service fully working
    depends_on:
      - db
    # Link the network to the container
    networks:
      - backend
    # Hot reload (does not work, gotta work on it)
    restart: always
# List of named volumes
# Allow to persist the volume even if the containers are down
volumes:
  pgdata:
  static_volume:
# List of networks
networks:
  backend:
