version: "3.8"
services:
  # The database service
  db:
    # Name the image
    image: postgres
    # Rename it postgres to avoid being named 'db-1'
    container_name: postgres
    env_file:
      - .env
    # Define every required environment variables
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_HOST: "${POSTGRES_HOST}"
      POSTGRES_PORT: "${POSTGRES_PORT}"
    # Create a volume to persist database data
    volumes:
      - pgdata:/var/lib/postgresql/data
    # Link the network to the container
    networks:
      - backend
  # The app service
  jizo:
    # Rename it jizo to avoid being named `jizo-1`
    container_name: jizo
    # Rename the image
    image: jizo_backend
    # Point to the prod.Dockerfile used for the build
    build:
      # prod.Dockerfile which is located in the same directory as the docker-compose.yaml
      context: .
      dockerfile: docker/prod.Dockerfile
    # Exposing ports
    expose:
      - 80
    # Mount the volume
    volumes:
      - .:/jizo
      - static_volume:/home/app/web/staticfiles
    # Command used to run the server
    command:
      gunicorn app.wsgi:application --bind 0.0.0.0:8000
    # Cannot be launched without the db service fully working
    depends_on:
      - db
    # Link the network to the container
    networks:
      - backend
  # The reserve proxy service
  nginx:
    # Rename it to nginx to avoid being name `nginx-1`
    container_name: nginx
    # Rename the image
    image: jizo_nginx
    # The folder where is located its Dockerfile
    build: ./nginx
    # Mount the volume
    volumes:
      - static_volume:/home/src/app/web/staticfiles
    # Port listening
    ports:
      - "8000:80"
    # Depends on the jizo container to work
    depends_on:
      - jizo
    # Link the network
    networks:
      - backend
# List of named volumes
# Allow to persist the volume even if the containers are down
volumes:
  pgdata:
  static_volume:
# List of networks
networks:
  backend: