# Generated by Django 4.2.5 on 2023-11-01 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aclRoute', '0001_initial'),
        ('aclBundle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AclBundleAclRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acl_bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aclBundle.aclbundle')),
                ('acl_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aclRoute.aclroute')),
            ],
            options={
                'db_table': 'aclbundle_aclroute',
            },
        ),
    ]
