# Generated by Django 4.2.5 on 2023-10-11 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aclBundle_aclRoute', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aclbundleaclroute',
            old_name='acl_bundle_id',
            new_name='acl_bundle',
        ),
        migrations.RenameField(
            model_name='aclbundleaclroute',
            old_name='acl_route_id',
            new_name='acl_route',
        ),
    ]
