# Generated by Django 4.2.10 on 2024-02-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='shortened',
            field=models.CharField(default='-', max_length=2),
            preserve_default=False,
        ),
    ]
