# Generated by Django 4.2.5 on 2023-10-07 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level',
            old_name='isActive',
            new_name='is_active',
        ),
        migrations.AlterModelTable(
            name='level',
            table='level',
        ),
    ]
