# Generated by Django 4.2.5 on 2023-10-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0002_rename_isactive_level_is_active_alter_level_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='is_active',
        ),
        migrations.AddField(
            model_name='level',
            name='is_activate',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
