# Generated by Django 4.2.5 on 2023-10-10 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aclBundle_aclRoute', '0001_initial'),
        ('aclBundle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aclbundle',
            name='bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aclBundle_aclRoute.aclbundleaclroute'),
        ),
    ]
