# Generated by Django 4.2.5 on 2023-10-10 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aclBundle', '0003_remove_aclbundle_bundle_aclbundle_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aclbundle',
            name='route',
        ),
    ]
