# Generated by Django 4.2.5 on 2023-10-11 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary_interest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itineraryinterest',
            old_name='interest_id',
            new_name='interest',
        ),
        migrations.RenameField(
            model_name='itineraryinterest',
            old_name='itinerary_id',
            new_name='itinerary',
        ),
    ]
