# Generated by Django 4.2.5 on 2023-10-07 09:43

import contract.constants
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0002_alter_role_table'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roleId',
            field=models.ForeignKey(default=contract.constants.Constants.Roles['ROLE_USER'], on_delete=django.db.models.deletion.CASCADE, to='role.role'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
