# Generated by Django 4.2.5 on 2023-10-11 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary_type', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itinerarytype',
            old_name='itinerary_id',
            new_name='itinerary',
        ),
        migrations.RenameField(
            model_name='itinerarytype',
            old_name='type_id',
            new_name='type',
        ),
    ]
