# Generated by Django 4.2.5 on 2023-10-07 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary_type', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='itinerarytype',
            table='itinerary_type',
        ),
    ]
