# Generated by Django 4.2.5 on 2023-10-11 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role_aclBundle', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roleaclbundle',
            old_name='acl_bundle_id',
            new_name='acl_bundle',
        ),
        migrations.RenameField(
            model_name='roleaclbundle',
            old_name='role_id',
            new_name='role',
        ),
    ]
