# Generated by Django 4.2.5 on 2023-10-10 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aclRoute', '0002_aclroute_bundle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aclroute',
            name='bundle',
        ),
    ]
